function gencenters(side, λ)
    volume = side^3
    points = pois_rand(λ*volume)
    return reduce(hcat, (rand(Float32, 3) for i in 1:points)) * side
end

function genspheres(side, λ, R)
    array = zeros(Bool, (side, side, side))
    centers = gencenters(side, λ)
    for center in (centers[:,i] for i in 1:size(centers,2))
        for k in -R:R
            for j in -R:R
                for i in -R:R
                    dist = sqrt(i^2 + j^2 + k^2)
                    if dist < R
                        x = center[1] - i |> floor |> Int
                        y = center[2] - j |> floor |> Int
                        z = center[3] - k |> floor |> Int
                        if x > 0 && x < side && y > 0 && y < side && z > 0 && z < side
                            array[x,y,z] = 1
                        end
                    end
                end
            end
        end
    end
    return array, size(centers,2)
end

s1_estimate(R, λ) = 4/3 * π*λ*R^3

@testset "S2 on random spheres generated by Poisson process" begin
    # 64 spheres in average of radius 12
    R = 12; λ = 1e-6
    f = mean ∘ s2
    spheres, _ = genspheres(400, λ, R)
    s = f(spheres, 50, 1)
    @test abs(s1_estimate(R, λ) - s[1]) < 1e-2
    @test all(s2 -> abs(s1_estimate(R, λ)^2 - s2) < 1e-2, s[20:end])
end
