name: CI

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: x64
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Test package
        uses: julia-actions/julia-runtest@v1
